### ISSUE TITLE
zvolenie licencie pre kódy projektu ECN

### ISSUE THREAD

**Issue by masaryk** [IoT-BA/ECN#1]

**Comment by masaryk** [comment]
@hecko @dejwoo , pls ak ste použili zdrojáky z iných projektov, môžete sem uviesť ich zoznam? je to dôležité, aby som sa pozrel na ich licencovanie. vďaka.

**Comment by masaryk** [comment]
zdroje k téme:
https://opensource.org/osd
http://www.zajtra.sk/technologie/325/open-source-licencie
http://www.kiwiki.info/index.php/Prehľad_open-source_licenci%C3%AD

**Comment by anton-pytel** [comment]
Mne príde MIT licencia celkom vhodná. Zbavuje zodpovednosti ak vyvinuté kódy niekto "zle" použije, ktokoľvek to môže využiť neskôr aj komerčne.

**Comment by masaryk** [comment]
tuto ochranu maju podla mna vsetky open source licencie. :)


Dňa so 28. 1. 2017 o 22:23 Anton Pytel <notifications@github.com>
napísala(a):

**Comment by masaryk** [comment]
we agreed to use MIT license for project Noe. as team informed me, used open-source libraries and products is also MIT licensed
