### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by masaryk** [IoT-BA/ECN#10]
choosing project name

**Comment by masaryk** [comment]
@hecko @dejwoo @anton-pytel @viktorhirschner 
máte pls návrh na iný názov projektu? rád by som to uzavrel .... vďaka.

**Comment by dejwoo** [comment]
Moj prvy nastrel je len mensia uprava: NoE - Net[work] of Everything.
mozno este: Project NoE
Skusim este nieco vymysliet.

**Comment by masaryk** [comment]
@dejwoo pekný návrh, nemal by som problém ani s týmto. :-)
@hecko co Ty na toto?

**Comment by masaryk** [comment]
finally we agree on name: "project Noe", **n**etwork **o**f **e**verything
